//! Generic "upload a folder as chunked Release assets" helper. Used by the
//! preview publisher to ship math files past GitHub Pages's 100 MB / file
//! limit. The output is a manifest with public `browser_download_url`s the
//! WASM runtime can stitch back together at play time.
//!
//! Mirrors the chunking strategy in `math_sync` (1 GiB chunks, SHA-suffixed
//! asset names so a partially-failed re-push is idempotent) but doesn't
//! depend on the team data model.

use anyhow::{Context, Result, anyhow};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::path::Path;
use tokio::fs;
use tokio::io::{AsyncReadExt, AsyncSeekExt};

use crate::github::api::GithubClient;

/// Progress callback signature. Invoked once per chunk uploaded (or skipped
/// because it was already on the release).
pub struct ChunkProgress<'a> {
    pub current_file: &'a str,
    pub file_index: u32,
    pub file_count: u32,
    pub bytes_done: u64,
    pub bytes_total: u64,
}

/// Max bytes per release asset. GitHub's published limit is 2 GiB, but
/// uploads get flaky well before that. 1 GiB is safe.
const CHUNK_SIZE: u64 = 1024 * 1024 * 1024;

/// Public-URL manifest written into the preview bundle. The WASM runtime
/// reads it and fetches chunks directly.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReleasedFile {
    /// Relative path in the source directory (forward slashes).
    pub name: String,
    pub size: u64,
    pub sha256: String,
    pub chunks: Vec<ReleasedChunk>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReleasedChunk {
    #[serde(rename = "assetName")]
    pub asset_name: String,
    /// Public download URL (`browser_download_url`) — works without auth.
    pub url: String,
    pub size: u64,
    pub sha256: String,
}

/// Upload `file_rel_paths` (relative to `src_dir`) to the release tagged
/// `tag` on `<owner>/<repo>`. Creates the release if it doesn't exist;
/// re-uploading is idempotent thanks to SHA-suffixed asset names.
///
/// `on_progress` is called once per chunk handled (uploaded or skipped).
pub async fn upload_dir<F>(
    client: &GithubClient,
    owner: &str,
    repo: &str,
    tag: &str,
    title: &str,
    src_dir: &Path,
    file_rel_paths: &[String],
    mut on_progress: F,
) -> Result<Vec<ReleasedFile>>
where
    F: FnMut(ChunkProgress<'_>),
{
    let release = match client.find_release_by_tag(owner, repo, tag).await? {
        Some(r) => r,
        None => {
            client
                .create_release(
                    owner,
                    repo,
                    tag,
                    title,
                    "Auto-generated by stake-dev-tool preview publisher.",
                )
                .await?
        }
    };

    let existing: std::collections::HashMap<String, &crate::github::api::ReleaseAsset> = release
        .assets
        .iter()
        .map(|a| (a.name.clone(), a))
        .collect();

    // Pre-compute total bytes so the progress bar can render a meaningful
    // percentage from chunk #1 onwards.
    let mut sizes: Vec<u64> = Vec::with_capacity(file_rel_paths.len());
    let mut bytes_total: u64 = 0;
    for rel in file_rel_paths {
        let meta = fs::metadata(src_dir.join(rel))
            .await
            .with_context(|| format!("stat {rel}"))?;
        sizes.push(meta.len());
        bytes_total += meta.len();
    }

    let mut out = Vec::with_capacity(file_rel_paths.len());
    let file_count = file_rel_paths.len() as u32;
    let mut bytes_done: u64 = 0;

    for (file_ix, rel) in file_rel_paths.iter().enumerate() {
        let path = src_dir.join(rel);
        let size = sizes[file_ix];
        let (whole_sha, chunk_metas) = hash_and_chunk(&path, size).await?;
        let total = chunk_metas.len() as u64;

        let mut chunks = Vec::with_capacity(chunk_metas.len());
        for (ix, (chunk_sha, chunk_size)) in chunk_metas.iter().enumerate() {
            let asset_name = chunk_asset_name(rel, ix as u64, total, chunk_sha);
            if let Some(existing_asset) = existing.get(&asset_name) {
                // Use the API URL (`/repos/.../releases/assets/{id}`) rather
                // than `browser_download_url`. The browser-download path
                // returns a 302 from github.com without CORS headers, so a
                // cross-origin fetch from github.io is blocked. The API URL
                // serves CORS headers and redirects to the S3 backend (which
                // also has CORS) when called with `Accept:
                // application/octet-stream`.
                chunks.push(ReleasedChunk {
                    asset_name: asset_name.clone(),
                    url: existing_asset.url.clone(),
                    size: *chunk_size,
                    sha256: chunk_sha.clone(),
                });
            } else {
                let bytes = read_chunk_bytes(&path, ix as u64, total, size).await?;
                let uploaded = client
                    .upload_release_asset(&release.upload_url, &asset_name, bytes)
                    .await
                    .with_context(|| format!("upload {asset_name}"))?;
                chunks.push(ReleasedChunk {
                    asset_name,
                    url: uploaded.url,
                    size: *chunk_size,
                    sha256: chunk_sha.clone(),
                });
            }
            bytes_done += *chunk_size;
            on_progress(ChunkProgress {
                current_file: rel,
                file_index: file_ix as u32,
                file_count,
                bytes_done,
                bytes_total,
            });
        }

        out.push(ReleasedFile {
            name: rel.clone(),
            size,
            sha256: whole_sha,
            chunks,
        });
    }

    Ok(out)
}

fn chunk_asset_name(file_rel_path: &str, part_ix: u64, total_parts: u64, sha: &str) -> String {
    let safe: String = file_rel_path
        .chars()
        .map(|c| if c == '/' || c == '\\' { '.' } else { c })
        .collect();
    let short = &sha[..8.min(sha.len())];
    if total_parts == 1 {
        format!("{safe}.{short}")
    } else {
        format!("{safe}.part{:03}.{short}", part_ix + 1)
    }
}

async fn hash_and_chunk(path: &Path, size: u64) -> Result<(String, Vec<(String, u64)>)> {
    let mut file = fs::File::open(path).await?;
    let mut whole = Sha256::new();
    let total_parts = if size == 0 { 1 } else { size.div_ceil(CHUNK_SIZE) };
    let mut chunks = Vec::with_capacity(total_parts as usize);
    let mut buf = vec![0u8; 1024 * 1024];

    for part_ix in 0..total_parts {
        let mut part_hasher = Sha256::new();
        let mut part_read: u64 = 0;
        let target = if part_ix + 1 == total_parts {
            size - part_ix * CHUNK_SIZE
        } else {
            CHUNK_SIZE
        };
        while part_read < target {
            let to_read = ((target - part_read) as usize).min(buf.len());
            let n = file.read(&mut buf[..to_read]).await?;
            if n == 0 {
                break;
            }
            whole.update(&buf[..n]);
            part_hasher.update(&buf[..n]);
            part_read += n as u64;
        }
        chunks.push((hex(&part_hasher.finalize()), part_read));
    }
    Ok((hex(&whole.finalize()), chunks))
}

async fn read_chunk_bytes(path: &Path, part_ix: u64, total_parts: u64, size: u64) -> Result<Vec<u8>> {
    let mut file = fs::File::open(path).await?;
    let offset = part_ix * CHUNK_SIZE;
    if offset > 0 {
        file.seek(std::io::SeekFrom::Start(offset)).await?;
    }
    let target = if part_ix + 1 == total_parts {
        size - offset
    } else {
        CHUNK_SIZE
    };
    let mut out = Vec::with_capacity(target as usize);
    let mut buf = vec![0u8; 4 * 1024 * 1024];
    let mut total: u64 = 0;
    while total < target {
        let to_read = ((target - total) as usize).min(buf.len());
        let n = file.read(&mut buf[..to_read]).await?;
        if n == 0 {
            break;
        }
        out.extend_from_slice(&buf[..n]);
        total += n as u64;
    }
    Ok(out)
}

fn hex(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{:02x}", b));
    }
    s
}
